    Array2
        1 - np.random.rand() //gets a shape give items between 0 ,1
        2 - np.random.randn() it's between -1  ,1
        3 - np.random.randint(low , high , shape)  // low inc , high exclusive
        4 - cells with the same seem get the same result for the random generator 
        5 - np.reshape # the items should be able to fit in there 
        6 - min , max , argmin , argmax # min , max , index of the min , index of the max
        7 - dtype : data type of the items in the numpy array   

In [2]:
import numpy as np

In [ ]:
np.random.rand(5 ,5) # this is using uniform distribution meaning that each number has the same chance

array([[0.33307201, 0.99227231, 0.62309672, 0.3355779 , 0.89258461],
       [0.69075304, 0.52749057, 0.66703076, 0.90909037, 0.90528268],
       [0.51857919, 0.01478815, 0.71557143, 0.02962427, 0.15928395],
       [0.87019724, 0.04529088, 0.72277708, 0.47252993, 0.31908529],
       [0.51870905, 0.03160303, 0.06905248, 0.25304945, 0.52928869]])

In [103]:
np.random.randn(10) #it's around zero and goes to 1 or -1

array([ 1.82736247, -1.40765191, -0.27716515,  0.5958267 , -0.89058545,
        0.61962709,  1.01697027, -1.57843454,  0.65693949, -1.56810796])

In [ ]:
# np.random.normal(0 , 10)  # not sure about this one 

9.051512823918507

In [170]:
np.random.randint(1  , 100 , (10 ,10)) # low , high (exclusive) , shape 

array([[51, 53, 86, 38, 52, 11, 55, 90, 58, 20],
       [ 2, 96, 94, 82, 62, 82,  5, 21, 15, 60],
       [55, 30, 33, 77, 14, 24, 10, 84, 56, 50],
       [ 5, 35,  3, 49, 51,  3, 80, 91, 48, 13],
       [ 8, 19, 31, 28, 13, 86, 24, 82, 15, 98],
       [ 5, 23, 86, 11, 24, 43, 43, 64, 66, 41],
       [14, 86, 99, 69,  8, 88, 55, 59, 93, 21],
       [77, 91, 98, 69, 29, 43, 58, 57, 26, 32],
       [76, 88, 14, 33, 69, 93, 57, 52, 13, 69],
       [53, 43, 26, 58, 47, 17, 25, 23, 67, 33]])

In [ ]:
np.random.seed(555)
np.random.rand(4)

NameError: name 'random' is not defined

In [ ]:
arr = np.arange(25)

In [ ]:
randomarray = np.random.randint(0 ,50 , 10 , dtype=int)

In [193]:
arr.reshape(5 , 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [200]:
randomarray.max()

49

In [201]:
randomarray.min()

1

In [ ]:
randomarray.argmax() # give the location of the maximum value 

3

In [206]:
randomarray.argmin() # gives the location of the minimum value 

4

In [209]:
randomarray.dtype

dtype('int64')