    *Indexing Selection 
        1 - slicing , the same as normal python 
        2 - 2D selection 
        3 - conditional selection .. arr[arr > 4] return the items of the arr that are 
            bigger than 4


In [98]:
import numpy as np
from math import *

In [11]:
arr = np.arange(0 , 11 , 1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(arr[1:5]) # simple slicing exclude the 5 (until the 4th index)
print(arr[10:5:-1]) # this is another same 
print(f'array sclice : \n{arr[0:10 : 2]}')

[1 2 3 4]
[10  9  8  7  6]
array sclice : 
[0 2 4 6 8]


In [ ]:
arr ** 2 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
slice_of_array  = arr[0:6]
slice_of_array[:] = 99
slice_of_array


array([99, 99, 99, 99, 99, 99])

In [43]:
array_copy = arr.copy()
array_copy[:] = 9
array_copy

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [44]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [53]:
#indexing on the 2d ARARY
array_2d = np.array([[1 ,2, 3], [4 ,5 ,6 ] , [7 , 8 , 9]])
array_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
array_2d.shape 

(3, 3)

In [ ]:
# indexing (slicing  ... )

print(f'1th row and second clumn: {array_2d[0][1]} ') # first column ,  this can be 
print(f'the second item of the first column : {array_2d[1][0]}')
print(f"the 3th row and third column is : {array_2d[2][2]}")
print(f"the right top(2,2) subsquare is : \n {array_2d[1: , :2]}") # 2d slicing of the array 

1th row and second clumn: 2 
the second item of the first column : 4
the 3th row and third column is : 9
the right top(2,2) subsquare is : 
 [[4 5]
 [7 8]]


In [95]:
arr = np.arange(1 ,11 , dtype=int)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
print(type(log(1024 , 2)))
print((log(1024 , 2)))

print((arr >=  log(10)))
bool_array = arr >= 2


<class 'float'>
10.0
[False False  True  True  True  True  True  True  True  True]


In [127]:
print(arr)
print(bool_array)
print(arr[bool_array])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True  True  True  True  True  True  True  True  True]
[ 2  3  4  5  6  7  8  9 10]


In [140]:
arr[arr == 2]

array([2])

In [ ]:
# operation propogation 