In [18]:
import numpy as np

In [45]:
x = np.arange(0, 10 , 1)


In [20]:
x + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [21]:
(x + 2) / 100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [22]:
x / 0

/tmp/ipykernel_91585/3814715862.py:1: RuntimeWarning: divide by zero encountered in divide
  x / 0
/tmp/ipykernel_91585/3814715862.py:1: RuntimeWarning: invalid value encountered in divide
  x / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [23]:
1 / x

/tmp/ipykernel_91585/65478251.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / x


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [31]:
x / x 

/tmp/ipykernel_91585/3754946187.py:1: RuntimeWarning: invalid value encountered in divide
  x / x


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [49]:
# np operations 
np.sin(x)
np.cos(x)
np.log(x)


/tmp/ipykernel_91585/3037520965.py:4: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
x.sum()
x.mean()
x.min()
x.max()


0

In [60]:
arr_2d = np.array([[1,2 ,3 ,4] , [5 ,6 ,7 ,9] , [10 ,11, 12, 13]])
arr_2d


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  9],
       [10, 11, 12, 13]])

In [ ]:
arr = arr_2d.sum(axis=0) # this is the sum of all columns (in other words give the sum accross the rows)
arr_1 = arr_2d.sum(axis=1) # this is the sum of all rows (give the sum accross the columns)

print(f"sum of rows  : {arr}")
print(f"sum of columns  : {arr_1}")

sum of rows  : [16 19 22 26]
sum of columns  : [10 27 46]
