In [1]:
import torch

In [41]:
# auto graidiant 
x = torch.tensor(2.0, requires_grad=True) # keep an eye on this 

- Function  y = 2x^4 + x^3 + 3x^2 + 5x + 1
- Derivative y' = 8x^3 + 3x^2 + 6x + 5


In [42]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x +1
y

tensor(63., grad_fn=<AddBackward0>)

In [43]:
y.backward()

In [ ]:
print(x.grad) # it is the awsner of passing the 2 in the first drivite of the y meaning y'(x)
# the slope of the thing in the w
# first we have to back propagate

tensor(93.)


In [49]:
x = torch.tensor([[1.0 , 2.0 , 3.0] , [3.0 , 2.0 , 1.0]] , requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [52]:
y = 3*x + 2
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [57]:
z = 2*y**2

In [59]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [ ]:
out_ = z.mean()
out_ # last layer

tensor(140., grad_fn=<MeanBackward0>)

In [ ]:
out_.backward()

In [ ]:
print(x.grad) # this can be solved using chain rule ... 

tensor([[10., 16., 22.],
        [22., 16., 10.]])
