Tenosor basics .

In [6]:
import torch
import numpy as np

In [8]:
torch.__version__

'2.6.0+cu124'

In [13]:
arr = np.array([1,2 ,3 ,4 ,5])
print(arr.dtype)

int64


In [ ]:
x = torch.from_numpy(arr) # jsut works for numpy array

torch.int64

In [22]:
torch.as_tensor(arr) # this one is a little more genralized .. 

tensor([1, 2, 3, 4, 5])

In [ ]:
arr_2d = np.arange(0.0 , 12.0)
arr_2d = arr_2d.reshape(4 ,3)


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
x2 = torch.from_numpy(arr_2d) # numpy array to pytorch tensor
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [36]:
arr[0] = 99

In [ ]:
my_arr = np.arange(0 , 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor = torch.tensor(my_arr) # this is a copy
my_arr[0] = 2
my_tensor


array([2, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_other_tensor = torch.from_numpy(my_arr) 

tensor([2, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# diffrence between torch.tensor , torch.Tensor
new_arr = np.array([1,2,3])
print(f"init dtype is : {new_arr.dtype}")
x_1 = torch.tensor(new_arr)
print(f"after dtype is : {x_1.dtype}")
x_2 = torch.Tensor(new_arr) # used for floating point
x_3 = torch.FloatTensor(new_arr) # exact same thing with the above .. 
print(f"after1 dtype is : {x_2.dtype}")
print(f"after2 dtype is : {x_3.dtype}")

init dtype is : int64
after dtype is : torch.int64
after1 dtype is : torch.float32
after2 dtype is : torch.float32


In [ ]:
torch.empty(5 ,5 ) # some placeholder for them .. 
torch.zeros(5 ,5) # actual zeros for them

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])