Tenosor basics .

In [270]:
import torch
import numpy as np

In [271]:
torch.__version__

'2.6.0+cu124'

In [272]:
arr = np.array([1,2 ,3 ,4 ,5])
print(arr.dtype)

int64


In [273]:
x = torch.from_numpy(arr) # jsut works for numpy array

In [274]:
torch.as_tensor(arr) # this one is a little more genralized .. 

tensor([1, 2, 3, 4, 5])

In [275]:
arr_2d = np.arange(0.0 , 12.0)
arr_2d = arr_2d.reshape(4 ,3)


In [276]:
x2 = torch.from_numpy(arr_2d) # numpy array to pytorch tensor
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [277]:
arr[0] = 99

In [278]:
my_arr = np.arange(0 , 10)

In [279]:
my_tensor = torch.tensor(my_arr) # this is a copy
my_arr[0] = 2
my_tensor


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [280]:
my_other_tensor = torch.from_numpy(my_arr) 

In [281]:
# diffrence between torch.tensor , torch.Tensor
new_arr = np.array([1,2,3])
print(f"init dtype is : {new_arr.dtype}")
x_1 = torch.tensor(new_arr)
print(f"after dtype is : {x_1.dtype}")
x_2 = torch.Tensor(new_arr) # used for floating point
x_3 = torch.FloatTensor(new_arr) # exact same thing with the above .. 
print(f"after1 dtype is : {x_2.dtype}")
print(f"after2 dtype is : {x_3.dtype}")

init dtype is : int64
after dtype is : torch.int64
after1 dtype is : torch.float32
after2 dtype is : torch.float32


In [282]:
torch.empty(5 ,5) # some placeholder for them .. 
torch.zeros(5 ,5 , dtype=torch.int64) # actual zeros for them
torch.ones(5 , 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [283]:
torch.arange(0 , 18 , 2).reshape(3 , 3)


tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [284]:
torch.linspace(0 , 18 ,12).reshape(3 ,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [285]:
torch.tensor([1,2 ,3])

tensor([1, 2, 3])

In [286]:
my_tensor = torch.tensor([1,2 ,3])
my_tensor = my_tensor.type(torch.int32)


In [287]:
torch.randn(4 ,3)

tensor([[-0.3786, -0.1859,  1.7446],
        [-0.3937, -0.3705,  0.5541],
        [-0.0330,  1.6497,  0.2662],
        [-1.5110, -0.1204, -1.5676]])

In [ ]:
torch.randint(low=0 , high=11 , size=(5 ,5)) 


tensor([[ 8, 10,  0,  2,  8],
        [ 6,  4,  2,  5,  1],
        [ 0,  2,  0,  1,  5],
        [ 1, 10,  5,  5, 10],
        [ 9,  8,  3,  6,  6]])

In [ ]:
x = torch.zeros(2 ,5) 

In [ ]:
torch.rand_like(x) # rand with the shape of x

tensor([[0.3334, 0.7091, 0.0285, 0.3484, 0.0411],
        [0.9598, 0.5509, 0.5488, 0.6538, 0.6939]])

In [ ]:
torch.randint_like(x , low=0 ,high=10 ) # uniform chance for them between low , high 

tensor([[7., 3., 3., 7., 5.],
        [4., 7., 5., 0., 6.]])

In [ ]:
torch.manual_seed(42) # guide to everything 
torch.rand(2 ,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])