In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3 ,2)


In [3]:
x[1 ,1]

tensor(3)

In [4]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [5]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x.view(2 ,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
x = x.reshape(2 ,5) # VIEW OR RESHAPE SONT ACTUALY CAHNGE THE THING THEY 

In [8]:
x = torch.arange(10)
x = x.reshape(2 ,5)


In [9]:
z = x.view(1 ,10)
z

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
x = torch.arange(11 , dtype=torch.float32 )
x.shape

torch.Size([11])

In [11]:
x.view(1,-1)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [19]:
a = torch.tensor([1 , 2 ,3] , dtype=torch.int32)
b = torch.tensor([4 , 5 ,6] , dtype=torch.int32)

# reshaping them ... 
a = a.reshape(3) 
b = b.reshape(3)

print(f"the a is : \n{a}\n")
print(f"the b is : \n{b}\n")

print(f"the a + b is \n{a + b}\n") 

the a is : 
tensor([1, 2, 3], dtype=torch.int32)

the b is : 
tensor([4, 5, 6], dtype=torch.int32)

the a + b is 
tensor([5, 7, 9], dtype=torch.int32)



In [13]:
a.mul_(b) # this is in inplcae meaning the result goes to a 

tensor([ 4, 10, 18], dtype=torch.int32)

In [14]:
a * b # eleemnt by element operation ...  the same a.mul(b)

tensor([ 16,  50, 108], dtype=torch.int32)

In [27]:
print(f"a is : \n{a}")
print(f"b is : \n{b}")
print(f"a.shape is : {a.shape}")
print(f"b.shape is : {b.shape}")

a is : 
tensor([1, 2, 3], dtype=torch.int32)
b is : 
tensor([4, 5, 6], dtype=torch.int32)
a.shape is : torch.Size([3])
b.shape is : torch.Size([3])


In [ ]:
a * b # same as a.mul(b)  ==> these two are the same ...  mul_ is inpalce for the first one 



tensor(32, dtype=torch.int32)

In [ ]:
a = torch.tensor([[0 , 2 ,4] , [1 ,3 ,5]])
b = torch.tensor([[6 ,7] , [8 ,9] , [10 ,11]])


a is : tensor([[0, 2, 4],
        [1, 3, 5]])
b is : tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])


In [41]:
torch.mm(a ,b) # normal matrix multipication ...  same as a @ b


tensor([[56, 62],
        [80, 89]])

In [ ]:
x = torch.tensor([2 ,3 ,4 ,5 ] , dtype=torch.float32)
x.norm()

tensor(7.3485)

In [51]:
a.numel() # number of elemts .. greate for n dimetional arrays
len(a) # just counts the things in the list .. 

2