In [2]:
import torch
import numpy as np

In [ ]:
x = torch.arange(6).reshape(3 ,2)


tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
x[1 ,1]

tensor(3)

In [10]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [13]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x.view(2 ,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
x = x.reshape(2 ,5) # VIEW OR RESHAPE SONT ACTUALY CAHNGE THE THING THEY 

In [48]:
x = torch.arange(10)
x = x.reshape(2 ,5)


In [58]:
z = x.view(1 ,10)
z

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [72]:
x = torch.arange(11 , dtype=torch.float32 )
x.shape

torch.Size([11])

In [73]:
x.view(1,-1)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [135]:
a = torch.tensor([1 , 2 ,3] , dtype=torch.int32)
b = torch.tensor([4 , 5 ,6] , dtype=torch.int32)

# reshaping them ... 
a = a.reshape(1 ,3) 
b = b.reshape(1 ,3)

print(f"the a is : \n{a}\n")
print(f"the b is : \n{b}\n")

print(f"the a + b is \n{a + b}\n") 

the a is : 
tensor([[1, 2, 3]], dtype=torch.int32)

the b is : 
tensor([[4, 5, 6]], dtype=torch.int32)

the a + b is 
tensor([[5, 7, 9]], dtype=torch.int32)



In [138]:
a.mul_(b) # this is in inplcae meaning the result goes to a 

tensor([[ 16,  50, 108]], dtype=torch.int32)

In [140]:
a

tensor([[ 16,  50, 108]], dtype=torch.int32)