In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
torch.manual_seed(42)
np.random.seed(42)

In [ ]:
np.random.seed(42) 
arr = np.random.randint(low=0 ,  high=5 , size=(1 , 6))


array([[3, 4, 2, 4, 4, 1]])

In [ ]:
my_tensor = torch.from_numpy(arr) # my_tensor1 = torch.as_tensor(arr)
my_tensor = my_tensor.type(torch.int64)
my_tensor.type()
my_tensor.dtype #kinda the same we the above 

'torch.LongTensor'

In [ ]:
my_tensor = my_tensor.reshape(3 ,2) # laso we can use .view(3 ,2)
print(f"my tensor is : \n{my_tensor}")
my_tensor[: ,1:] # kinda the same as sciling  ..

my tensor is : 
tensor([[3, 4],
        [2, 4],
        [4, 1]])


tensor([[4],
        [4],
        [1]])

In [ ]:
my_tensor ** 2 # operation exantion or something like this ...

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [91]:
torch.manual_seed(42)
my_tensor2 = torch.randint(low=0 , high=5 , size=(2 ,3))
my_tensor2

tensor([[2, 2, 1],
        [4, 1, 0]])

In [ ]:
torch.mm(my_tensor , my_tensor2) # or x.mm(y) .. 


tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])